todos/config/routes.rb
Todos::Application.routes.draw do
  resources :todos

end

todos/app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :completed, :due_on, :name
end

todos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

todos/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = Todo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(params[:todo])

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, :notice => 'Todo was successfully created.' }
        format.json { render :json => @todo, :status => :created, :location => @todo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @todo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to @todo, :notice => 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @todo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end
end

todos/app/helpers/application_helper.rb
module ApplicationHelper
end

todos/app/helpers/todos_helper.rb
module TodosHelper
end

todos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

todos/app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_on %><br />
    <%= f.date_select :due_on %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

todos/app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

todos/app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Due on</th>
    <th>Completed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.name %></td>
    <td><%= todo.due_on %></td>
    <td><%= todo.completed %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo', new_todo_path %>

todos/app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

todos/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @todo.name %>
</p>

<p>
  <b>Due on:</b>
  <%= @todo.due_on %>
</p>

<p>
  <b>Completed:</b>
  <%= @todo.completed %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>